portais = {
    "O TEMPO ONLINE - BELO HORIZONTE - MG": {
        'abrangencia': 'Local',
        'codigo': 'O Tempo',
        'url': 'https://www.otempo.com.br/',
        'prioridade': 'Alta',
        'pontos': '20',
    },
    "ESTADO DE MINAS ONLINE - BELO HORIZONTE - MG": {
        'abrangencia': 'Local',
        'codigo': 'Estado de Minas',
        'url': 'https://www.em.com.br/',
        'prioridade': 'Alta',
        'pontos': '15',
    },
    "DIÁRIO DO COMÉRCIO ONLINE - MG": {
        'abrangencia': 'Local',
        'codigo': 'Diário do Comércio',
        'url': 'https://diariodocomercio.com.br/',
        'prioridade': 'Alta',
        'pontos': '7',
    },
    "HOJE EM DIA ONLINE - BELO HORIZONTE - MG": {
        'abrangencia': 'Local',
        'codigo': 'Hoje em Dia (MG)',
        'url': 'https://www.hojeemdia.com.br/minas',
        'prioridade': 'Alta',
        'pontos': '12',
    },
    "O GLOBO ONLINE - RJ": {
        'abrangencia': 'Nacional',
        'codigo': 'Portal O Globo',
        'url': 'https://oglobo.globo.com/',
        'prioridade': 'Alta',
        'pontos': '35',
    },
    "FOLHA ONLINE - SP": {
        'abrangencia': 'Nacional',
        'codigo': 'Folha de SP',
        'url': 'https://www.folha.uol.com.br/',
        'prioridade': 'Alta',
        'pontos': '25',
    },
    "BH EVENTOS- BELO HORIZONTE - MG": {
        'abrangencia': 'Local',
        'codigo': 'BH Eventos',
        'url': 'https://bheventos.com.br/',
        'prioridade': 'Baixa',
        'pontos': '10',
    },
    "BHAZ": {
        'abrangencia': 'Local',
        'codigo': 'BHAZ',
        'url': 'https://bhaz.com.br/',
        'prioridade': 'Média',
        'pontos': '15',
    },
    "CODEMGE": {
        'abrangencia': 'Local',
        'codigo': 'CODEMGE',
        'url': '',
        'prioridade': '',
        'pontos': '',
    },
    "FIEMG": {
        'abrangencia': 'Local',
        'codigo': 'FIEMG',
        'url': '',
        'prioridade': '',
        'pontos': '',
    },
    "G1 - MINAS GERAIS - MG": {
        'abrangencia': 'Local',
        'codigo': 'G1 Minas',
        'url': 'https://g1.globo.com/mg/minas-gerais/',
        'prioridade': 'Alta',
        'pontos': '15',
    },
    "JORNAL PANORAMA ONLINE": {
        'abrangencia': '',
        'codigo': 'Jornal Panorama',
        'url': '',
        'prioridade': '',
        'pontos': '',
    },
    "O CONTORNO DE BH": {
        'abrangencia': 'Local',
        'codigo': 'O Contorno de BH',
        'url': '',
        'prioridade': '',
        'pontos': '',
    },
    "PORTAL VIRALIZA BH": {
        'abrangencia': 'Local',
        'codigo': 'Portal Viraliza BH',
        'url': '',
        'prioridade': '',
        'pontos': '',
    },
    "REVISTA ISTO É DINHEIRO ONLINE": {
        'abrangencia': 'Nacional',
        'codigo': 'Revista Isto É',
        'url': 'https://istoe.com.br/',
        'prioridade': 'Média',
        'pontos': '10',
    },
}
