palavras_obrigatorias = [
    "Minas Gerais",
    "MG",
    "Minas"
]

palavras_adicionais = [
    "Zema",
    "Romeu",
    "Professor Mateus",
    "Prof. Mateus",
    "Mateus Simões",
    "RRF",
    "Regime de Recuperação Fiscal",
    "Dívida de Minas com a União",
    "Dívida dos Estados",
    "Eleição 2024",
    "Eleição municipal",
    "Eleição 2026",
    "Eleição estadual",
    "Metrô",
    "Metrô de BH",
    "PIB",
    "Agronegócio mineiro",
    "Turismo de Minas",
    "Vacinação",
    "Mineiridade",
    "Brumadinho",
    "Barragem de Brumadinho",
    "Barragem de Mariana",
    "Mariana",
    "Mineração",
    "Projeto Apolo",
    "Barragens",
    "Barragens em Minas",
    "Vale do Lítio",
    "Jequitinhonha",
    "Hospital Regional",
    "Hospitais Regionais",
    "Escolas estaduais",
    "Secretaria de Estado de Comunicação Social",
    "Secretária Geral do Estado",
    "Secretaria de Estado de Agricultura, Pecuária e Abastecimento",
    "Secretaria de Estado de Casa Civil",
    "Secretaria de Estado de Cultura e Turismo",
    "Secretaria de Estado de Desenvolvimento Econômico",
    "Secretaria de Estado de Desenvolvimento Social",
    "Secretaria de Estado de Educação",
    "Secretaria de Estado de Fazenda",
    "Secretaria de Estado de Governo",
    "Secretaria de Estado de Infraestrutura, Mobilidade e Parcerias",
    "Secretaria de Estado de Justiça e Segurança Pública",
    "Secretaria de Estado de Meio Ambiente e Desenvolvimento Sustentável",
    "Secretaria de Estado de Planejamento e Gestão",
    "Secretaria de Estado de Saúde",
    "SECOM",
    "SEAPA",
    "SCC",
    "SECULT",
    "SEDE",
    "SEDESE",
    "SEE",
    "SEF",
    "SEGOV",
    "SEINFRA",
    "SEJUSP",
    "SEMAD",
    "SEPLAG",
    "SES",
    "Codemge",
    "Copasa",
    "Cemig",
    "BDMG",
    "Epamig",
    "Fhemig",
    "DER",
    "Governo de Minas",
    "Governo de Minas Gerais",
    "Governo do Estado de Minas Gerais",
    "Governador"
]
